<a href="https://colab.research.google.com/github/HunterCoders/Prostate-Cancer-Detection-Random-Forest/blob/main/Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install kaggle

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
! mkdir ~/.kaggle

In [ ]:
!cp /content/drive/MyDrive/Colab_Notebooks/Kaggle_API/kaggle.json ~/.kaggle

In [ ]:
! chmod 600 ~/.kaggle/kaggle.json

In [ ]:
! kaggle datasets download soujanyahp/prostate-cancer-dataset

  0% 0.00/2.51k [00:00<?, ?B/s]
100% 2.51k/2.51k [00:00<00:00, 5.35MB/s]


In [ ]:
! unzip /content/prostate-cancer-dataset.zip

Archive:  /content/prostate-cancer-dataset.zip
  inflating: prostate.csv            


In [ ]:
!pip install DataSynthesizer

In [ ]:
# Data Processing
import pandas as pd
import numpy as np

# Modelling
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, ConfusionMatrixDisplay
from sklearn.model_selection import RandomizedSearchCV, train_test_split
from scipy.stats import randint

# Tree Visualisation
from sklearn.tree import export_graphviz
from IPython.display import Image
import graphviz
from sklearn.ensemble import GradientBoostingRegressor
import imblearn

In [ ]:
file=pd.read_csv('/content/prostate.csv')

In [ ]:
# prompt:
file.head(100)

lcavol   lweight  age      lbph  svi       lcp  gleason  pgg45  \
0  -0.579818  2.769459   50 -1.386294    0 -1.386294        6      0   
1  -0.994252  3.319626   58 -1.386294    0 -1.386294        6      0   
2  -0.510826  2.691243   74 -1.386294    0 -1.386294        7     20   
3  -1.203973  3.282789   58 -1.386294    0 -1.386294        6      0   
4   0.751416  3.432373   62 -1.386294    0 -1.386294        6      0   
..       ...       ...  ...       ...  ...       ...      ...    ...   
92  2.830268  3.876396   68 -1.386294    1  1.321756        7     60   
93  3.821004  3.896909   44 -1.386294    1  2.169054        7     40   
94  2.907447  3.396185   52 -1.386294    1  2.463853        7     10   
95  2.882564  3.773910   68  1.558145    1  1.558145        7     80   
96  3.471966  3.974998   68  0.438255    1  2.904165        7     20   

        lpsa  train  
0  -0.430783   True  
1  -0.162519   True  
2  -0.162519   True  
3  -0.162519   True  
4   0.371564   True  
..       ...    ...  
92  4.385147   True  
93  4.684443   True  
94  5.143124  False  
95  5.477509   True  
96  5.582932  False  

[97 rows x 10 columns]

In [ ]:
file.head()

lcavol   lweight  age      lbph  svi       lcp  gleason  pgg45      lpsa  \
0 -0.579818  2.769459   50 -1.386294    0 -1.386294        6      0 -0.430783   
1 -0.994252  3.319626   58 -1.386294    0 -1.386294        6      0 -0.162519   
2 -0.510826  2.691243   74 -1.386294    0 -1.386294        7     20 -0.162519   
3 -1.203973  3.282789   58 -1.386294    0 -1.386294        6      0 -0.162519   
4  0.751416  3.432373   62 -1.386294    0 -1.386294        6      0  0.371564   

   train  
0   True  
1   True  
2   True  
3   True  
4   True

In [ ]:
file.isnull().sum()
file["train"] = file["train"].astype(int)
file.head(100)

lcavol   lweight  age      lbph  svi       lcp  gleason  pgg45  \
0  -0.579818  2.769459   50 -1.386294    0 -1.386294        6      0   
1  -0.994252  3.319626   58 -1.386294    0 -1.386294        6      0   
2  -0.510826  2.691243   74 -1.386294    0 -1.386294        7     20   
3  -1.203973  3.282789   58 -1.386294    0 -1.386294        6      0   
4   0.751416  3.432373   62 -1.386294    0 -1.386294        6      0   
..       ...       ...  ...       ...  ...       ...      ...    ...   
92  2.830268  3.876396   68 -1.386294    1  1.321756        7     60   
93  3.821004  3.896909   44 -1.386294    1  2.169054        7     40   
94  2.907447  3.396185   52 -1.386294    1  2.463853        7     10   
95  2.882564  3.773910   68  1.558145    1  1.558145        7     80   
96  3.471966  3.974998   68  0.438255    1  2.904165        7     20   

        lpsa  train  
0  -0.430783      1  
1  -0.162519      1  
2  -0.162519      1  
3  -0.162519      1  
4   0.371564      1  
..       ...    ...  
92  4.385147      1  
93  4.684443      1  
94  5.143124      0  
95  5.477509      1  
96  5.582932      0  

[97 rows x 10 columns]

In [ ]:
file.to_csv('/content/finalset.csv')

In [ ]:
filets=pd.read_csv('/content/finalset.csv')
filets.head(5)

Unnamed: 0    lcavol   lweight  age      lbph  svi       lcp  gleason  \
0           0 -0.579818  2.769459   50 -1.386294    0 -1.386294        6   
1           1 -0.994252  3.319626   58 -1.386294    0 -1.386294        6   
2           2 -0.510826  2.691243   74 -1.386294    0 -1.386294        7   
3           3 -1.203973  3.282789   58 -1.386294    0 -1.386294        6   
4           4  0.751416  3.432373   62 -1.386294    0 -1.386294        6   

   pgg45      lpsa  train  
0      0 -0.430783      1  
1      0 -0.162519      1  
2     20 -0.162519      1  
3      0 -0.162519      1  
4      0  0.371564      1

In [ ]:
# SMOTE Comparison
X1=file.iloc[:,1:-1]
y1=file.iloc[:,-1]

unique,count=np.unique(y1,return_counts=True)
unique,count

(array([0, 1]), array([30, 67]))

In [ ]:
from sklearn.model_selection import train_test_split
X_train_res1, X_test1, y_train_res1, y_test1 = train_test_split(
X1, y1, test_size=0.2, random_state=5)

In [ ]:
rf1 = RandomForestClassifier()
rf1.fit(X_train_res1, y_train_res1)
y_pred1 = rf1.predict(X_test1)
accuracy = accuracy_score(y_test1, y_pred1)
print("Accuracy: %.2f%%"%(accuracy*100))

Accuracy: 65.00%


In [ ]:
from imblearn.over_sampling import SMOTE
sm=SMOTE(random_state=25)
X_train2, y_train2 = sm.fit_resample(X_train_res1, y_train_res1)

unique,count=np.unique(y_train2,return_counts=True)
unique,count

(array([0, 1]), array([51, 51]))

In [ ]:
from sklearn.model_selection import train_test_split
X_train_res2, X_test2, y_train_res2, y_test2 = train_test_split(
X_train2, y_train2, test_size=0.2, random_state=1)

In [ ]:
rf2 = RandomForestClassifier()
rf2.fit(X_train_res2, y_train_res2)
y_pred2 = rf2.predict(X_test2)
accuracy = accuracy_score(y_test2, y_pred2)
print("Accuracy: %.2f%%"%(accuracy*100))

Accuracy: 85.71%


In [ ]:
from DataSynthesizer.DataDescriber import DataDescriber
from DataSynthesizer.DataGenerator import DataGenerator
from DataSynthesizer.ModelInspector import ModelInspector
from DataSynthesizer.lib.utils import read_json_file, display_bayesian_network
# input dataset

input_data='/content/finalset.csv'
# location of two output files
mode = '/content/correlated_attribute_mode'
description_file = f'/content/description.json'
synthetic_data = f'/content/sythetic_data.csv'
candidate_keys={'Pid':True}
categorical_attributes = {"Pid":True,"lcavol":True	,"lweight":True	,"age"	:True	,"lbph":True	,	"svi":True	,	"lcp"	:True	,"gleason"	:True	,"pgg45"	:True	,"lpsa"	:True	,"train":True	}
# An attribute is categorical if its domain size is less than this threshold.
threshold_value = 20
# A parameter in Differential Privacy. It roughly means that removing a row in the input dataset will not
# change the probability of getting the same output more than a multiplicative difference of exp(epsilon).
# Increase epsilon value to reduce the injected noises. Set epsilon=0 to turn off differential privacy.
epsilon = 1
# The maximum number of parents in Bayesian network, i.e., the maximum number of incoming edges.
degree_of_bayesian_network = 2
# Number of tuples generated in synthetic dataset.
num_tuples_to_generate = 10000
#candidate_keys = {'Unnamed': True}
describer = DataDescriber(category_threshold=threshold_value)
describer.describe_dataset_in_correlated_attribute_mode(dataset_file=input_data, epsilon=epsilon, k=degree_of_bayesian_network,attribute_to_is_candidate_key=candidate_keys)
describer.save_dataset_description_to_file(description_file)
display_bayesian_network(describer.bayesian_network)
generator = DataGenerator()
generator.generate_dataset_in_correlated_attribute_mode(num_tuples_to_generate, description_file)
generator.save_synthetic_data(synthetic_data)
# Read both datasets using Pandas.
synthetic_df = pd.read_csv('/content/sythetic_data.csv')
org_df = '/content/finalset.csv'
# Read attribute description from the dataset description file.
# attribute_description = read_json_file(description_file)['attribute_description']
# inspector = ModelInspector(org_df, synthetic_df, attribute_description)
# inspector.mutual_information_heatmap()

In [ ]:
file.to_csv('/content/finalset.csv')

In [ ]:
filets=pd.read_csv('/content/sythetic_data.csv')
filets.head()

Unnamed: 0    lcavol   lweight   age      lbph  svi       lcp  gleason  \
0           0  3.522398  4.156574  59.0  2.174995    1  2.457172        8   
1           1  2.466439  3.533182  53.0  2.303647    1  1.416155        8   
2           2 -0.204781  4.257076  78.0  2.007251    0  2.501079        8   
3           3 -1.280169  3.948632  48.0 -1.149298    1  2.477205        8   
4           4  1.627484  2.562938  71.0  1.795352    0  0.902877        7   

   pgg45      lpsa  train  
0     35  5.548841      1  
1     90  0.832238      1  
2     80  1.885613      0  
3     75  5.217797      1  
4     90  0.249422      0

In [ ]:
from sklearn.preprocessing import StandardScaler

# Assuming 'data' is your DataFrame containing the columns
columns_to_normalize = ['lcavol', 'lweight', 'age', 'lbph', 'svi', 'lcp', 'gleason', 'pgg45', 'lpsa']

# Initialize the scaler
scaler = StandardScaler()

# Fit and transform the data for the specified columns
filets[columns_to_normalize] = scaler.fit_transform(filets[columns_to_normalize])

In [ ]:
filets.head(5)

Unnamed: 0    lcavol   lweight       age      lbph       svi       lcp  \
0           0  1.567434  0.836930 -0.129260  1.534606  0.924259  1.358101   
1           1  0.846393 -0.058197 -0.668968  1.651484  0.924259  0.524210   
2           2 -0.977597  0.981240  1.579815  1.382214 -1.081947  1.393272   
3           3 -1.711904  0.538347 -1.118725 -1.485445  0.924259  1.374148   
4           4  0.273529 -1.451369  0.950156  1.189709 -1.081947  0.113057   

    gleason     pgg45      lpsa  train  
0  0.392185 -0.279018  1.722891      1  
1  0.392185  1.381552 -1.022292      1  
2  0.392185  1.079630 -0.409201      0  
3  0.392185  0.928669  1.530215      1  
4 -0.496518  1.381552 -1.361506      0

In [ ]:
X=filets.iloc[:,1:-1]
y=filets.iloc[:,-1]

In [ ]:
X,y

(        lcavol   lweight       age      lbph       svi       lcp   gleason  \
 0     1.567434  0.836930 -0.129260  1.534606  0.924259  1.358101  0.392185   
 1     0.846393 -0.058197 -0.668968  1.651484  0.924259  0.524210  0.392185   
 2    -0.977597  0.981240  1.579815  1.382214 -1.081947  1.393272  0.392185   
 3    -1.711904  0.538347 -1.118725 -1.485445  0.924259  1.374148  0.392185   
 4     0.273529 -1.451369  0.950156  1.189709 -1.081947  0.113057 -0.496518   
 ...        ...       ...       ...       ...       ...       ...       ...   
 9995  0.884120  1.405092  0.140594  0.194062  0.924259 -0.731067  0.392185   
 9996 -1.100349  0.709232 -1.298627  0.572400 -1.081947  1.255956 -0.496518   
 9997  1.119230  0.073937  1.130059 -0.853172 -1.081947 -0.466228  1.280888   
 9998  1.351207  1.095205 -1.568481  1.507435  0.924259  0.728049 -1.385221   
 9999  1.698682 -1.591481  1.579815 -1.322355 -1.081947  0.417654  1.280888   
 
          pgg45      lpsa  
 0    -0.279018  1.722

In [ ]:
unique,count=np.unique(y,return_counts=True)
unique,count

(array([0, 1]), array([4944, 5056]))

In [ ]:
from imblearn.over_sampling import SMOTE
sm=SMOTE(random_state=25)
X_train, y_train = sm.fit_resample(X, y)

In [ ]:
unique,count=np.unique(y_train,return_counts=True)
unique,count

(array([0, 1]), array([5056, 5056]))

In [ ]:
from sklearn.model_selection import train_test_split
X_train_res, X_test, y_train_res, y_test = train_test_split(
X, y, test_size=0.2, random_state=10)

In [ ]:
X_test

In [ ]:
rf = RandomForestClassifier()
rf.fit(X_train_res, y_train_res)

In [ ]:
y_pred = rf.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%"%(accuracy*100))

Accuracy: 87.65%


In [ ]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = list(range(2,50))
# Minimum number of samples required at each leaf node
min_samples_leaf = list(range(1,10))
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [ ]:
# Create a random forest classifier
rf = RandomForestClassifier()

# Use random search to find the best hyperparameters
rand_search = RandomizedSearchCV(rf,
                                 param_distributions = random_grid,
                                 n_iter = 30, cv = 5, verbose=2, random_state=42, n_jobs = -1)

# Fit the random search object to the data
rand_search.fit(X_train_res, y_train_res)

In [ ]:
best_rf = rand_search.best_estimator_

# Print the best hyperparameters
print('Best hyperparameters:',  rand_search.best_params_)

Best hyperparameters: {'n_estimators': 1000, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 'auto', 'max_depth': 80, 'bootstrap': False}


In [ ]:
y_pred = best_rf.predict(X_test)

In [ ]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: %.2f%%"%(accuracy*100))

In [ ]:
y_pred = best_rf.predict(X_test)
# Create the confusion matrix
cm = confusion_matrix(y_test, y_pred)
ConfusionMatrixDisplay(confusion_matrix=cm).plot();

In [ ]:
import numpy as np
from sklearn.metrics import f1_score
f1_score(y_test, y_pred, average='macro')
f1_score(y_test, y_pred, average='micro')
f1_score(y_test, y_pred, average='weighted')
# f1_score(y_test, y_pred, average=None)

0.8840293635333092

In [ ]:
import numpy as np
from sklearn.metrics import precision_score
y_true = y_test
y_pred = y_pred
precision_score(y_true, y_pred, average='macro')
precision_score(y_true, y_pred, average='micro')
precision_score(y_true, y_pred, average='weighted')
precision_score(y_true, y_pred, average=None)

array([0.87145749, 0.89624506])

In [ ]:
import numpy as np
from sklearn import metrics
fpr, tpr, thresholds = metrics.roc_curve(y_true, y_pred, pos_label=1)
metrics.auc(fpr, tpr)

0.8842401816499874

In [ ]:
pred1=best_rf.predict(np.array([[-1.203973,	3.282789,	58,	-1.386294,	0,	-1.386294,	6,	0,	-0.162519]]))
pred2=best_rf.predict(np.array([[3.471966,	3.974998,	68,	0.438255,	1,	2.904165,	7,	20,	5.582932]]))
print(pred1,pred2)

[0] [1]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [ ]:
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

# Assuming y_true and y_pred are your ground truth labels and predicted labels respectively
# Replace them with your actual data


# Calculate precision, recall, and F1 score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

# Display the results in a matrix format
print("Metrics   | Score")
print("------------------")
print(f"Precision | {precision:.4f}")
print(f"Recall    | {recall:.4f}")
print(f"F1 Score  | {f1:.4f}")


Metrics   | Score
------------------
Precision | 0.8962
Recall    | 0.8772
F1 Score  | 0.8866


In [ ]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,y_pred)

0.116

In [3]:
!git remote add origin https://HunterCoders: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@github.com/HunterCoders/Prostate-Cancer-Detection-Random-Forest.git


fatal: not a git repository (or any of the parent directories): .git
